// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $Car from "./islands/Car.tsx";
import * as $Traffic from "./islands/Traffic.tsx";
import * as $UiWrapper from "./islands/UiWrapper.tsx";
import * as $traffic_machine_context from "./islands/traffic-machine-context.ts";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Car.tsx": $Car,
    "./islands/Traffic.tsx": $Traffic,
    "./islands/UiWrapper.tsx": $UiWrapper,
    "./islands/traffic-machine-context.ts": $traffic_machine_context,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
