name: Deploy
on:
  push:
    branches: [traffix-lights/version-1]
  pull_request:
    branches: traffix-lights/version-1

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Build step
        run: "deno cache --reload dev.ts && deno cache --reload main.ts && deno task build" # 📝 Update the build command(s) if necessary
        # TODO remove sleep


      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "traffic-v1" # 📝 Update the deploy project name if necessary
          entrypoint: "main.ts" # 📝 Update the entrypoint if necessary
